// Auto-generated by sync-nodes.js - DO NOT EDIT MANUALLY
import { lazy } from 'react';

export { nodeMetadata } from './nodeMetadataRegistry';

export const nodeComponents = {
  Embed: lazy(() => import('./embed/NodeComponent')),
  EmbedImages: lazy(() => import('./embed_images/NodeComponent')),
  GeocodeAgent: lazy(() => import('./geocode_agent/NodeComponent')),
  ImageEnrich: lazy(() => import('./image_enrich/NodeComponent')),
  JSONInput: lazy(() => import('./json_input/NodeComponent')),
  LLMEnrich: lazy(() => import('./llm_enrich/NodeComponent')),
  OrganizationsExtract: lazy(() => import('./organizations_extract/NodeComponent')),
  Output: lazy(() => import('./output/NodeComponent')),
  PeopleExtract: lazy(() => import('./people_extract/NodeComponent')),
  PlaceExtract: lazy(() => import('./place_extract/NodeComponent')),
  PlaceFilter: lazy(() => import('./place_filter/NodeComponent')),
  StatsNode: lazy(() => import('./stats/NodeComponent')),
  TextInput: lazy(() => import('./text_input/NodeComponent')),
  WorksExtract: lazy(() => import('./works_extract/NodeComponent')),
};

export const panelComponents = {
  Embed: lazy(() => import('./embed/PanelComponent')),
  EmbedImages: lazy(() => import('./embed_images/PanelComponent')),
  GeocodeAgent: lazy(() => import('./geocode_agent/PanelComponent')),
  ImageEnrich: lazy(() => import('./image_enrich/PanelComponent')),
  JSONInput: lazy(() => import('./json_input/PanelComponent')),
  LLMEnrich: lazy(() => import('./llm_enrich/PanelComponent')),
  OrganizationsExtract: lazy(() => import('./organizations_extract/PanelComponent')),
  Output: lazy(() => import('./output/PanelComponent')),
  PeopleExtract: lazy(() => import('./people_extract/PanelComponent')),
  PlaceExtract: lazy(() => import('./place_extract/PanelComponent')),
  PlaceFilter: lazy(() => import('./place_filter/PanelComponent')),
  StatsNode: lazy(() => import('./stats/PanelComponent')),
  TextInput: lazy(() => import('./text_input/PanelComponent')),
  WorksExtract: lazy(() => import('./works_extract/PanelComponent')),
};

export const visualizationComponents = {
  GeocodeAgent: () => import('./geocode_agent/VisualizationComponent'),
  OrganizationsExtract: () => import('./organizations_extract/VisualizationComponent'),
  PeopleExtract: () => import('./people_extract/VisualizationComponent'),
  WorksExtract: () => import('./works_extract/VisualizationComponent'),
};

export type NodeType = keyof typeof nodeComponents;
export type PanelType = keyof typeof panelComponents;
export type VisualizationType = keyof typeof visualizationComponents;
